platform :ios, '9.0'
use_frameworks!


target "codemash" do
    pod 'Alamofire', '4.0.1'
	pod 'ObjectMapper', '2.2.1'
	pod 'AlamofireImage', '3.1.0'
	pod 'Google-Mobile-Ads-SDK', '7.11.0'
	pod 'ReachabilitySwift', '~> 3'

	pod 'pop', '1.0.9'
end




post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['SWIFT_VERSION'] = "3.0"
    end
  end
end